definitions:
  domain.Dentist:
    properties:
      id:
        type: integer
      lastname:
        type: string
      name:
        type: string
      registration:
        type: string
    required:
    - id
    - lastname
    - name
    - registration
    type: object
  domain.Patient:
    properties:
      DNI:
        type: string
      dischargedate:
        type: string
      home:
        type: string
      id:
        type: integer
      lastname:
        type: string
      name:
        type: string
    type: object
  domain.Shift:
    properties:
      dentist_id:
        type: integer
      description:
        type: string
      dischargedate:
        type: string
      id:
        type: integer
      patient_id:
        type: integer
    required:
    - description
    - dischargedate
    type: object
info:
  contact: {}
paths:
  /dentists:
    patch:
      consumes:
      - application/json
      description: update a field dentist
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dentist
        in: body
        name: dentist
        required: true
        schema:
          $ref: '#/definitions/domain.Dentist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: dentist
      summary: update a field dentist
      tags:
      - Dentist
    post:
      consumes:
      - application/json
      description: create dentist
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dentist
        in: body
        name: dentist
        required: true
        schema:
          $ref: '#/definitions/domain.Dentist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: dentist
      summary: create a dentist
      tags:
      - Dentist
    put:
      consumes:
      - application/json
      description: update dentist
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dentist
        in: body
        name: dentist
        required: true
        schema:
          $ref: '#/definitions/domain.Dentist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: dentist
      summary: update a dentist
      tags:
      - Dentist
  /dentists/{id}:
    delete:
      consumes:
      - application/json
      description: deletes dentist by id
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Dentist id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: dentist
      summary: deletes a dentist
      tags:
      - Dentist
    get:
      consumes:
      - application/json
      description: get dentist by id
      parameters:
      - description: Dentist id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: dentist
      summary: get a dentist
      tags:
      - Dentist
  /patients:
    get:
      consumes:
      - application/json
      description: get all patients
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patients
      summary: get all patients
      tags:
      - Patient
    patch:
      consumes:
      - application/json
      description: update a field patient
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Patient
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/domain.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patient
      summary: update a field patient
      tags:
      - Patient
    post:
      consumes:
      - application/json
      description: get patient by id
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: patient
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/domain.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patient
      summary: create a patient
      tags:
      - Patient
    put:
      consumes:
      - application/json
      description: update patient
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Patient
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/domain.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patient
      summary: update a patient
      tags:
      - Patient
  /patients/{id}:
    delete:
      consumes:
      - application/json
      description: deletes patient by id
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Patient
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patient
      summary: deletes a patient
      tags:
      - Patient
    get:
      consumes:
      - application/json
      description: get patients by id
      parameters:
      - description: Patient id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: patients
      summary: get a patient
      tags:
      - Patient
  /shifts:
    patch:
      consumes:
      - application/json
      description: update a field shift
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shift
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/domain.Shift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: update a field shift
      tags:
      - Shift
    post:
      consumes:
      - application/json
      description: get shift by id
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shift
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/domain.Shift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: create a shift
      tags:
      - Shift
    put:
      consumes:
      - application/json
      description: update shift
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shift
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/domain.Shift'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: update a shift
      tags:
      - Shift
  /shifts/{dni}:
    get:
      consumes:
      - application/json
      description: get a shift by dni
      parameters:
      - description: dni
        in: path
        name: dni
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: get a shift by dni
      tags:
      - Shift
  /shifts/{dni}/{registration}:
    post:
      consumes:
      - application/json
      description: create a shift by dni and registration
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shift
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/domain.Shift'
      - description: dni
        in: path
        name: dni
        required: true
        type: string
      - description: registration
        in: path
        name: registration
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: create a shift by dni and registration
      tags:
      - Shift
  /shifts/{id}:
    delete:
      consumes:
      - application/json
      description: deletes shift by id
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Shift
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shift
      summary: deletes a shift
      tags:
      - Shift
    get:
      consumes:
      - application/json
      description: get shifts by id
      parameters:
      - description: Shift id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: shifts
      summary: get a shift
      tags:
      - Shift
swagger: "2.0"
